server:
  port: 8080

spring:
  application:
    name: NCT

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    
    
  # MySQL 등 spring-jdbc 사용 시 아래 정보 없으면 서버 가동 시 에러
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wearup?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: nct200
    password: 1234
  
  security:
    user:
      name: user
      password: 1234


app:
  #페이징 세팅값
  pagination:
    write_pages: 10 # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10 # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?
  
  #파일 업로드 경로
  upload:
    path: upload


# MyBatis 매퍼(mapper) 파일(*.xml) 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # resources/mapper 이하의 모든 xml 파일을 대상으로 함
  configuration:
    map-underscore-to-camel-case: true
