server:
  port: 80

spring:
  application:
    name: WEARUP
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


  # MySQL 등 spring-jdbc 사용 시 아래 정보 없으면 서버 가동 시 에러
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${rds.username}
    password: ${rds.password}

  security:
    #OAuth2 client
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - ${NAVER_SCOPE_NAME}
              - ${NAVER_SCOPE_EMAIL}
            client-name: ${NAVER_CLIENT_NAME}
            authorization-grant-type: ${NAVER_AUTH_TYPE}
            redirect-uri: ${NAVER_REDIRECT_URI}

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATICATION_METHOD}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            redirect-uri: ${KAKAO_REDIRECT_URI}

            scope:
              - ${KAKAO_SCOPE}
            client-name: ${KAKAO_CLIENT_NAME}


        # provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response   # 사용자 이름: response/name (response 속성 내에 존재)

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  servlet:
    multipart:
      # 파일 크기 제한 설정
      max-file-size: 1000MB     # default = 1MB
      max-request-size: 1000MB  #default = 10MB

  # MyBatis 매퍼(mapper) 파일(*.xml) 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # resources/mapper 이하의 모든 xml 파일을 대상으로 함
  configuration:
    map-underscore-to-camel-case: true

app:
  #파일 업로드 경로
  upload:
    path:
      post: upload/post
      item: upload/item
      brand: upload/brand
