INSERT INTO Item (brand_id, name, category, is_available, item_status, is_exist, description)
VALUES (1, '더뮤지엄비지터 21FW 러브 바시티 자켓', '의류', TRUE, 'A', TRUE, '포근한 보온감과 세련된 디자인을 갖춘 자켓입니다.'),
       (1, '엠제이드가방', '가방', FALSE, 'B', TRUE, '캐주얼한 룩에 포인트를 줄 수 있는 멋스러운 가방입니다.'),
       (1, 'LETQ STUDIO Puffy mini dress, black', '의류', TRUE, 'C', TRUE, '볼륨감 있는 실루엣이 돋보이는 블랙 미니 드레스입니다.'),
       (1, '미세키서울 니트', '의류', TRUE, 'A', TRUE, '부드러운 촉감과 깔끔한 핏이 매력적인 니트 상의입니다.'),
       (1, 'MEENDERI-SLUB KNIT BOLERO CARDIGAN - SALMON', '의류', FALSE, 'B', TRUE, '화사한 살몬 컬러의 볼레로 가디건으로 봄 스타일링에 잘 어울립니다.'),
       (1, '마뗑킴 반팔', '의류', TRUE, 'C', TRUE, '경쾌한 컬러감과 가벼운 착용감이 특징인 반팔 티셔츠입니다.'),
       (1, 'MEENDERI Ruffle Lace Sleeveless Top - Black', '의류', FALSE, 'A', TRUE, '레이스 디테일이 돋보이는 시크한 블랙 슬리브리스 탑입니다.'),
       (1, '에잇세컨즈 나시', '의류', TRUE, 'B', TRUE, '심플한 디자인으로 다양한 스타일에 매치하기 좋은 나시 탑입니다.'),
       (1, '데이신드롬 TICKLE CREWNECK KNIT olive', '의류', FALSE, 'C', TRUE, '부드러운 올리브 컬러 크루넥 니트로 데일리 룩에 적합합니다.'),
       (1, 'Ma Journee NECK POINT RIBBED TOP_BROWN', '의류', TRUE, 'A', TRUE, '빈티지한 브라운 컬러의 골지 탑으로 포인트를 줄 수 있습니다.'),
       (1, '레이스 상의', '의류', TRUE, 'B', TRUE, '섬세한 레이스 디테일이 돋보이는 여성스러운 상의입니다.'),
       (2, 'carier 사각 프레임 안경', '악세서리', FALSE, 'C', TRUE, '심플하면서도 모던한 매력이 돋보이는 사각 프레임 안경입니다.'),
       (2, 'Adidas Originals Track Top Light Grey - KR Sizing', '의류', TRUE, 'A', TRUE, '편안한 그레이 컬러 트랙탑으로 활동적인 룩에 잘 어울립니다.'),
       (2, '멀티 카고 팬츠', '의류', TRUE, 'B', TRUE, '다양한 포켓 디테일로 실용성과 스타일을 동시에 갖춘 팬츠입니다.'),
       (2, 'G CLASSIC WASHED BALL CAP', '악세서리', FALSE, 'C', TRUE, '빈티지한 워시드 컬러로 캐주얼 룩에 포인트를 줄 수 있는 볼캡입니다.'),
       (2, '메인부스 스웨트 오트밀', '의류', TRUE, 'A', TRUE, '따뜻한 오트밀 컬러의 스웨트로 편안한 데일리 스타일을 완성합니다.'),
       (2, '뮤엘 론 스트라이프 오버핏 셔츠', '의류', FALSE, 'B', TRUE, '넉넉한 실루엣의 스트라이프 셔츠로 트렌디한 오버핏을 제공합니다.'),
       (2, 'Supra Garment Dying Crown Spray Hood Gray', '의류', TRUE, 'C', TRUE, '그레이 컬러로 워시 처리된 후디로 편안한 착용감을 선사합니다.'),
       (2, '샤넬 19 백 스몰', '가방', TRUE, 'A', TRUE, '고급스러운 체인 스트랩과 큼직한 로고가 돋보이는 스몰 백입니다.'),
       (2, 'Sunburn Cap Charcoal', '악세서리', FALSE, 'B', TRUE, '차콜 컬러의 볼캡으로 자외선 차단과 스타일을 동시에 잡아줍니다.'),
       (2, '테켓 Pining Cap Brown', '악세서리', TRUE, 'C', TRUE, '브라운 컬러의 핍 모자가 빈티지 무드를 완성해줍니다.'),
       (2, 'CELINE 보니 백팩', '가방', TRUE, 'A', TRUE, '고급스러운 가죽 소재로 제작된 세련된 디자인의 백팩입니다.'),
       (2, 'TOMMY JEANS 데님 오버롤 팬츠', '의류', FALSE, 'B', TRUE, '캐주얼한 데님 오버롤로 데일리 코디에 활용도가 높습니다.'),
       (3, '션 존 올드스쿨 빅사이즈 데님 자켓', '의류', TRUE, 'C', TRUE, '빈티지 워싱이 돋보이는 빅사이즈 데님 자켓으로 개성 있는 룩을 완성합니다.'),
       (3, 'Zara X Studio Nicholson Oversize Wool Blazer Black', '의류', FALSE, 'A', TRUE, '블랙 울 소재의 오버사이즈 블레이저로 포멀한 무드를 연출합니다.'),
       (3, '로우 데님 자켓', '의류', TRUE, 'B', TRUE, '심플한 디자인의 중청 데님 자켓으로 어디에나 잘 어울립니다.'),
       (3, 'Mother Typographic Cotton T-Shirt', '의류', TRUE, 'C', TRUE, '부드러운 코튼 소재와 타이포그래픽 프린트가 돋보이는 티셔츠입니다.'),
       (3, '느와르라르메스', '의류', FALSE, 'A', TRUE, '유니크한 디자인의 자켓으로 도회적이면서도 세련된 느낌을 줍니다.'),
       (3, '플루크 오버핏 데님 셔켓 FDJ101', '의류', TRUE, 'B', TRUE, '오버핏 실루엣이 멋스러운 데님 셔켓으로 캐주얼 룩에 제격입니다.'),
       (3, '도영 반팔', '의류', TRUE, 'C', TRUE, '편안한 착용감의 반팔 티셔츠로 다양한 스타일에 매치하기 좋습니다.')
;

INSERT INTO Item (Item.brand_id, name, category, is_available, item_status, is_exist, description)
VALUES (1, 'Supreme Utility Bag Black', '잡화', true, 'A', true, 'Supreme Utility Bag Black 입니다.'),
       (2, 'Arsenal 2024/25 Home Jersey Better Scarlet White', '상의', false, 'B', true, 'Arsenal 2024/25 Home Jersey Better Scarlet White 입니다.'),
       (1, 'Nike x Lil Yachty Us Force 1', '신발', true, 'C', true, 'Nike x Lil Yachty Us Force 1 입니다.'),
       (2, 'Supreme x Nike Track Jacket Purple', '아우터', true, 'A', true, 'Supreme x Nike Track Jacket Purple 입니다.'),
       (1, 'Nonnod Side Cargo Shorts Beige', '하의', false, 'B', true, 'Nonnod Side Cargo Shorts Beige 입니다.'),
       (2, 'Nike Korea 2022/23 Dri-Fit ADV Player Issue Home Global Red', '하의', true, 'C', true, 'Nike Korea 2022/23 Dri-Fit ADV Player Issue Home Global Red 입니다.'),
       (1, 'Taw&Toe x Sanrio Flip Flop Zerovity Plumpy Hello Kitty Charm Tag Set Silver', '신발', true, 'A', true, 'Taw&Toe x Sanrio Flip Flop Zerovity Plumpy Hello Kitty Charm Tag Set Silver 입니다.'),
       (2, 'Sanrio Hello Kitty Mini Mascot Holder', '잡화', false, 'B', true, 'Sanrio Hello Kitty Mini Mascot Holder 입니다.'),
       (1, 'Millo Archive Denim Bermuda Pants', '하의', true, 'C', true, 'Millo Archive Denim Bermuda Pants 입니다.'),
       (2, 'Montbell Trekking Glasses', '잡화', true, 'A', true, 'Montbell Trekking Glasses 입니다.'),
       (1, 'Nike Stride Repel UV Running Jacket Black', '아우터', false, 'B', true, 'Nike Stride Repel UV Running Jacket Black 입니다.'),
       (2, 'Nike Brasilia 9.5 Training Duffle Bag', '잡화', true, 'C', true, 'Nike Brasilia 9.5 Training Duffle Bag 입니다.'),
       (1, 'Nike ZoomX Vaporfly Next% 3', '신발', true, 'A', true, 'Nike ZoomX Vaporfly Next% 3 입니다.'),
       (2, 'Nike NSW Woven Shorts Black', '하의', false, 'B', true, 'Nike NSW Woven Shorts Black 입니다.'),
       (1, 'BAPE ABC Camo College T-Shirt', '상의', true, 'C', true, 'BAPE ABC Camo College T-Shirt 입니다.'),
       (2, 'Emis New Logo Pigment Ball Cap', '잡화', true, 'A', true, 'Emis New Logo Pigment Ball Cap 입니다.'),
       (1, 'Helen Kaminski Bianca Natural Black Logo', '잡화', false, 'B', true, 'Helen Kaminski Bianca Natural Black Logo 입니다.'),
       (2, 'Uniqlo UT x Kaws Short Sleeve Graphic T-Shirt', '상의', true, 'C', true, 'Uniqlo UT x Kaws Short Sleeve Graphic T-Shirt 입니다.'),
       (1, 'Play Comme des Garcons Double Heart T-Shirt White', '상의', true, 'A', true, 'Play Comme des Garcons Double Heart T-Shirt White 입니다.'),
       (2, '47 Brand LA Dodgers Clean Up Royal', '잡화', false, 'B', true, '47 Brand LA Dodgers Clean Up Royal 입니다.')
;

INSERT INTO ItemAttachment (item_id, sourcename, filename)
VALUES (1,  'post001.png',  'post001.png'),
       (2,  'post002.jpg',  'post002.jpg'),
       (3,  'post003.png',  'post003.png'),
       (4,  'post004.png',  'post004.png'),
       (5,  'post005.png',  'post005.png'),
       (6,  'post006.png',  'post006.png'),
       (7,  'post007.png',  'post007.png'),
       (8,  'post008.png',  'post008.png'),
       (9,  'post009.png',  'post009.png'),
       (10, 'post010.png',  'post010.png'),
       (11, 'post011.png',  'post011.png'),
       (12, 'post101.png',  'post101.png'),
       (13, 'post102.png',  'post102.png'),
       (14, 'post103.png',  'post103.png'),
       (15, 'post104.png',  'post104.png'),
       (16, 'post105.jpg',  'post105.jpg'),
       (17, 'post106.jpg',  'post106.jpg'),
       (18, 'post107.png',  'post107.png'),
       (19, 'post108.png',  'post108.png'),
       (20, 'post109.png',  'post109.png'),
       (21, 'post110.png',  'post110.png'),
       (22, 'post111.png',  'post111.png'),
       (23, 'post112.png',  'post112.png'),
       (24, 'post202.png',  'post202.png'),
       (25, 'post201.png',  'post201.png'),
       (26, 'post203.png',  'post203.png'),
       (27, 'post204.png',  'post204.png'),
       (28, 'post205.png',  'post205.png'),
       (29, 'post206.png',  'post206.png'),
       (30, 'post207.png',  'post207.png'),
       (31, 'item1.png', '92495f77-385c-412b-a5c1-5867bf792cfe_item1.png'),
       (32, 'item2.png', '245c1a47-1f8f-452c-b023-22edcf335630_item2.png'),
       (33, 'item3.png', '4a3fc2b2-774e-4519-876c-df5d4049b113_item3.png'),
       (34, 'item4.png', 'd704dd9e-cd09-45f4-9450-49075c011667_item4.png'),
       (35, 'item5.png', 'be1d8b66-db9a-48b6-b5d2-3e9e17cc37a5_item5.png'),
       (36, 'item6.png', '5bbaa18e-ee99-4973-87ac-7f29516f05c8_item6.png'),
       (37, 'item7.png', 'd9fdb8de-1b1a-4408-b61c-06747d12e57a_item7.png'),
       (38, 'item8.png', 'c1a15017-8f3d-46b0-80fe-6ccdd4287994_item8.png'),
       (39, 'item9.png', '81b910db-f88e-4962-9ba4-2405c0ffbe6b_item9.png'),
       (40, 'item10.png', '849d9893-1bb3-43f8-8c3f-9ce170fdf0ac_item10.png'),
       (41, 'item11.png', '6afbdcc2-22de-427c-b1cb-92b36fc47996_item11.png'),
       (42, 'item12.png', '232b5314-f104-4de8-ab20-66543b5d3943_item12.png'),
       (43, 'item13.png', '036ea3c9-bd21-47ed-a951-4089f6bee24f_item13.png'),
       (44, 'item14.png', '82e02fb1-ef17-48ce-860d-a97c91ad704e_item14.png'),
       (45, 'item15.png', '715a1d80-ed2f-40c0-90c4-67919f941c45_item15.png'),
       (46, 'item16.png', '2583ae15-e02f-479b-9ee0-a31b512688df_item16.png'),
       (47, 'item17.png', '789f71dd-daf7-41bd-8336-10c3875b81db_item17.png'),
       (48, 'item18.png', '56367c8a-3f62-4d08-858d-7415c38e6763_item18.png'),
       (49, 'item19.png', '084a3de1-eecc-4a8d-8c0b-baff09de9de6_item19.png'),
       (50, 'item20.png', 'bd48e167-ee2a-4a56-8744-dd8cb28f332a_item20.png')
;
